[build]
  command = "bash build.sh"
  publish = "dist"

[[redirects]]
  from = "/structsolve"
  to = "/structsolve/index.html"
  status = 200

[[redirects]]
  from = "/structsolve/"
  to = "/structsolve/index.html"
  status = 200

[[redirects]]
  from = "/structsolve/*"
  to = "/structsolve/index.html"
  status = 200

[[redirects]]
  from = "/rootfinder"
  to = "/rootfinder/index.html"
  status = 200

[[redirects]]
  from = "/rootfinder/"
  to = "/rootfinder/index.html"
  status = 200

[[redirects]]
  from = "/rootfinder/*"
  to = "/rootfinder/index.html"
  status = 200
